version: '3.8'

services:
  tags-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "tags-db"

  tags-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "YourStrongPassword"
      ACCEPT_EULA: "Y"